replicaCount: 1

elasticsearchHosts: "http://elasticsearch-master:9200"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Remove affinity for Minikube compatibility
affinity: {}